import { sql } from 'drizzle-orm';
import { migrate } from 'drizzle-orm/libsql/migrator';
import db from '../index';

export async function runMigrations() {
  await migrate(db, { migrationsFolder: './src/database/migrations' });
}

// This is a placeholder - actual migrations will be generated by Drizzle Kit
